In [28]:
import pandas as pd

df_games = pd.read_csv('/home/user1/project/fifa_prediction/results.csv')
df_ranking = pd.read_csv('/home/user1/project/fifa_prediction/wc_2026_48_teams_fifa_rank_change_corrected.csv')
df_group_stage = pd.read_csv('/home/user1/project/fifa_prediction//group_stages.csv', sep=';')
df_knockout_fixtures = pd.read_csv('/home/user1/project/fifa_prediction/fixtures_knockout_wc2026.csv')


pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [20]:
df_games.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [21]:
df_games.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [24]:
df_ranking.head()

      Nation  FIFA_2022_ranking  FIFA_2026_rank  rank_change
0     France                  3               1            2
1      Spain                 10               2            8
2  Argentina                  2               3           -1
3    England                  5               4            1
4   Portugal                  9               5            4

In [25]:
df_ranking['Nation'].unique()

array(['France', 'Spain', 'Argentina', 'England', 'Portugal', 'Brazil',
       'Netherlands', 'Morocco', 'Belgium', 'Germany', 'Croatia',
       'Colombia', 'Senegal', 'Mexico', 'United States', 'Uruguay',
       'Japan', 'Switzerland', 'Iran', 'Turkey', 'Ecuador', 'Austria',
       'South Korea', 'Australia', 'Algeria', 'Egypt', 'Canada', 'Norway',
       'Panama', 'Ivory Coast', 'Sweden', 'Paraguay', 'Czech Republic',
       'Scotland', 'Tunisia', 'DR Congo', 'Uzbekistan', 'Qatar', 'Iraq',
       'South Africa', 'Saudi Arabia', 'Jordan', 'Bosnia and Herzegovina',
       'Cape Verde', 'Ghana', 'Curaçao', 'Haiti', 'New Zealand'],
      dtype=object)

In [26]:
print(df_group_stage.shape)
df_group_stage.head()

(48, 3)

  group  position          nation
0     A         1          Mexico
1     A         2    South Africa
2     A         3     South Korea
3     A         4  Czech Republic
4     B         1          Canada

In [27]:
print(df_knockout_fixtures.shape)
df_knockout_fixtures.head()

(32, 8)

,match_id,round,match_date,match_time,home_slot,away_slot,winner_advances_to,loser_advances_to
0,M73,R32,2026-06-28,20:00,2A,2B,M90,NaN
1,M74,R32,2026-06-29,21:30,1E,3ABCDF,M89,NaN
2,M75,R32,2026-06-30,02:00,1F,2C,M90,NaN
3,M76,R32,2026-06-29,18:00,1C,2F,M91,NaN
4,M77,R32,2026-06-30,22:00,1I,3CDFGH,M89,NaN